---
- name: Install Evilnginx
  hosts: 66.228.62.183
  become: yes
  tasks:

    - name: Update apt package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install packages
      package:
        name: tmux
        state: present
      with_items:
        - tmux
        - golang-go
        - git
        - make

    - name: Set up Go environment variables
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "{{ item }}"
      with_items:
        - 'export GOPATH=$HOME/go'
        - 'export PATH=$PATH:$GOPATH/bin'
      when: ansible_os_family == 'Debian'
    - name: Clone the evilnginx2 repository
      git:
        repo: https://github.com/BakkerJan/evilginx2.git
        dest: "{{ansible_env.home}}/"
      register: git_clone_result
    - name: Print Clone result
      debug:
        var: git_clone_result
- name: Install covenant
  hosts: 66.228.62.183
  become: yes
  tasks:
    - name: Download Microsoft package repository configuration
        get_url:
          url: https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb
          dest: /tmp/packages-microsoft-prod.deb  # Specify the destination path for the downloaded file
          mode: 0644  # Set the file mode

      - name: Install the Microsoft package repository
        apt:
          deb: /tmp/packages-microsoft-prod.deb
          state: present
