all:
  hosts:
    phish.knowit.pictures:
      ansible_host: 66.228.62.183
    c2.knowit.pictures:
      ansible_host: 45.79.214.73
phish:
  hosts:
    phish.knowit.pictures:
c2:
  hosts:
    c2.knowit.pictures:
