all:
  hosts:
    phish-debian-eu-central:
      ansible_host: 172.105.246.68
    c2-debian-eu-west:
      ansible_host: 109.74.202.94
phish:
  hosts:
    phish-debian-eu-central:
c2:
  hosts:
    c2-debian-eu-west:
