---
- name: Install Evilnginx
  hosts: phish
  become: yes
  tags: evilginx
  tasks:
    - name: Update apt package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - tmux
        - golang-go
        - git
        - make
      tags:
        - install
        - packages

    - name: Set up Go environment variables
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "{{ item }}"
      with_items:
        - 'export GOPATH=$HOME/go'
        - 'export PATH=$PATH:$GOPATH/bin'
    - name: Clone the evilnginx2 repository
      git:
        repo: https://github.com/BakkerJan/evilginx2.git
        dest: "{{ansible_env.HOME}}/evilginx2"
      register: git_clone_result
    - name: Build Evilginx2
      shell: make
      args:
        executable: /bin/bash
        chdir: "{{ansible_env.HOME}}/evilginx2"
    - name: Build Evilginx2
      shell: make install
      args:
        executable: /bin/bash
        chdir: "{{ansible_env.HOME}}/evilginx2"
- name: Install covenant
  hosts: c2
  become: yes
  tags: covenant
  tasks:
    - name: Remove Native docker
      package:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker.io
        - docker-doc  
        - docker-compose
        - podman-docker
        - containerd
        - runc
    - name: Update apt package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
    - name: Install Packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - ca-certificates
        - curl
        - gnupg
        - git
        - tmux
    - name: Create the directory with specific permissions
      command: install -m 0755 -d /etc/apt/keyrings
    - name: Download Docker GPG Key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor  --yes -o /etc/apt/keyrings/docker.gpg
      args:
        executable: /bin/bash
    - name: Set Permissions for Docker GPG Key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'
    - name: Get the system architecture
      shell: dpkg --print-architecture
      register: system_architecture
    - name: Get Debian version
      shell: . /etc/os-release && echo "$VERSION_CODENAME"
      register: debian_version
    - name: Create Docker APT Repository Entry
      copy:
        content: |
          deb [arch="{{ system_architecture.stdout }}" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "{{ debian_version.stdout }}" stable
        dest: /etc/apt/sources.list.d/docker.list
      when: not ansible_check_mode 
    - name: Update apt package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
    - name: Install Docker
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce 
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        - python3-pip
    - name: Install Docker Python Packages
      pip:
        name: "{{ item }}"
      with_items:
        - docker
        - PyYaml
        - docker-compose
    - name: Create data directory if it does not exist
      ansible.builtin.file:
        path: "/opt/data"
        state: directory
        mode: '0755'
    - name: Clone the Git Repository with Submodules
      git:
        repo: https://github.com/reinthal/Covenant
        dest: "{{ansible_env.HOME}}/Covenant" 
        version: master  
        recursive: yes 
    - name: Copy Docker Compose File
      copy:
        src: covenant/docker-compose.yaml
        dest: "{{ansible_env.HOME}}/Covenant/Covenant/docker-compose.yaml"
    - name: Run docker compose
      community.docker.docker_compose:
        project_src: "{{ansible_env.HOME}}/Covenant/Covenant"
        files:
        - docker-compose.yaml
